server.port=8081
spring.application.name=photobooth-app
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
dslr.capture.folder=C:/Users/Admin/Pictures
camera.type=canon
printer.name=Canon SELPHY CP1500
